[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "AWS"
  pageRef = "aws"
  weight = 20

[[main]]
  name = "DevOps"
  pageRef = "devops"
  weight = 30

[[main]]
  name = "Homelab"
  pageRef = "homelab"
  weight = 40

[[main]]
  name = "Networking"
  pageRef = "networking"
  weight = 50

[[main]]
  name = "15-Min Teardowns"
  pageRef = "15min-teardowns"
  weight = 60

[[main]]
  name = "AI/ML"
  pageRef = "ai"
  weight = 55
